-- ============================================================================
-- Flutter Analytics Database Schema for Neon
-- ============================================================================
-- Purpose: Track anonymous usage analytics for Flutter app
-- Database: Neon PostgreSQL (Serverless)
-- ============================================================================

-- ============================================================================
-- TABLE 1: app_sessions
-- Purpose: Main analytics table - one row per app launch
-- ============================================================================
CREATE TABLE IF NOT EXISTS app_sessions (
    id BIGSERIAL PRIMARY KEY,
    
    -- Session & User
    session_id VARCHAR(255) NOT NULL,
    user_id_hash VARCHAR(255),
    timestamp TIMESTAMPTZ NOT NULL,
    
    -- Device Info
    device_model VARCHAR(255),
    device_brand VARCHAR(255),
    device_manufacturer VARCHAR(255),
    device_id_hash VARCHAR(255),
    
    -- Screen Info
    screen_width INTEGER,
    screen_height INTEGER,
    screen_density DECIMAL(10, 2),
    supported_abis TEXT,
    
    -- OS Info
    os_name VARCHAR(100) NOT NULL,
    os_version VARCHAR(100),
    api_level INTEGER,
    kernel_version VARCHAR(255),
    
    -- App Info
    app_version VARCHAR(50),
    app_build_number VARCHAR(50),
    package_name VARCHAR(255),
    is_first_launch BOOLEAN,
    install_source VARCHAR(255),
    launch_count INTEGER,
    
    -- Network Info
    network_type VARCHAR(50),
    carrier_name VARCHAR(255),
    ip_address INET,
    
    -- Locale Info
    locale_language VARCHAR(10),
    locale_country VARCHAR(10),
    timezone VARCHAR(100),
    timezone_offset INTEGER,
    currency VARCHAR(10),
    
    -- Performance Metrics
    startup_time_ms INTEGER,
    memory_usage_mb INTEGER,
    available_storage_gb DECIMAL(10, 2),
    
    -- Geolocation (enriched server-side)
    geo_country VARCHAR(100),
    geo_region VARCHAR(100),
    geo_city VARCHAR(100),
    geo_latitude DECIMAL(10, 6),
    geo_longitude DECIMAL(10, 6),
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- TABLE 2: app_events
-- Purpose: Track in-app user behavior (features used, conversions)
-- ============================================================================
CREATE TABLE IF NOT EXISTS app_events (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_name VARCHAR(255) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    properties JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- TABLE 3: app_errors
-- Purpose: Automatic crash and error reporting for debugging
-- ============================================================================
CREATE TABLE IF NOT EXISTS app_errors (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    error_type VARCHAR(255),
    error_message TEXT,
    stack_trace TEXT,
    context JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES for Performance
-- ============================================================================

-- app_sessions indexes
CREATE INDEX IF NOT EXISTS idx_sessions_session_id ON app_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id_hash ON app_sessions(user_id_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_timestamp ON app_sessions(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON app_sessions(created_at DESC);

-- app_events indexes
CREATE INDEX IF NOT EXISTS idx_events_session_id ON app_events(session_id);
CREATE INDEX IF NOT EXISTS idx_events_event_type ON app_events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON app_events(timestamp DESC);

-- app_errors indexes
CREATE INDEX IF NOT EXISTS idx_errors_session_id ON app_errors(session_id);
CREATE INDEX IF NOT EXISTS idx_errors_timestamp ON app_errors(timestamp DESC);

-- ============================================================================
-- COMMENTS for documentation
-- ============================================================================
COMMENT ON TABLE app_sessions IS 'Main analytics table - tracks each app launch with device and environment info';
COMMENT ON TABLE app_events IS 'User behavior tracking - features used, screen views, interactions';
COMMENT ON TABLE app_errors IS 'Automatic error and crash reporting for debugging and stability monitoring';

COMMENT ON COLUMN app_sessions.session_id IS 'Unique session identifier generated by client';
COMMENT ON COLUMN app_sessions.user_id_hash IS 'Anonymous user identifier (hashed device fingerprint)';
COMMENT ON COLUMN app_sessions.is_first_launch IS 'True if this is the first time user opens the app';
COMMENT ON COLUMN app_events.properties IS 'Flexible JSON field for event-specific data';
COMMENT ON COLUMN app_errors.context IS 'Additional context for debugging (screen name, user action, etc.)';

-- ============================================================================
-- Complete! Run this in the Neon SQL Editor to create your schema.
-- ============================================================================
